// Purpose: Contains constants used throughout the project.
// list of pretext commands
export const ptxCommandList = [
  {
    label: "Build default target",
    description: "",
    command: "pretext-tools.buildLast",
  },
  {
    label: "Build another target...",
    description: "select target",
    command: "pretext-tools.buildAny",
  },
  {
    label: "Preview file with CodeChat",
    description: "show in CodeChat preview",
    command: "pretext-tools.viewCodeChat",
  },
  {
    label: "View full document",
    description: "select target to view",
    command: "pretext-tools.viewCLI",
  },
  {
    label: "Deploy",
    description: "to GitHub Pages",
    command: "pretext-tools.deploy",
  },
  {
    label: "Refresh targets",
    description: "Refresh the list of targets",
    command: "pretext-tools.refreshTargets",
  },
  {
    label: "Convert to PreTeXt",
    description: "Convert from other formats using Pandoc",
    command: "pretext-tools.convert",
  },
  {
    label: "Run commands in terminal",
    description: "Use to debug a failed command",
    command: "pretext-tools.selectPretextCommand",
  },
];


// dictionary of pretext equivalents to latex environments
export const tex2ptxBlocks: { [key: string]: string } = {
  axiom: "axiom",
  principle: "principle",
  conjecture: "conjecture",
  heuristic: "heuristic",
  hypothesis: "hypothesis",
  assumption: "assumption",
  theorem: "theorem",
  thm: "theorem",
  lemma: "lemma",
  lem: "lemma",
  corollary: "corollary",
  cor: "corollary",
  claim: "claim",
  proposition: "proposition",
  prop: "proposition",
  algorithm: "algorithm",
  fact: "fact",
  identity: "identity",
  proof: "proof",
  definition: "definition",
  def: "definition",
  defn: "definition",
  remark: "remark",
  note: "note",
  warning: "warning",
  convention: "convention",
  observation: "observation",
  insight: "insight",
  example: "example",
  question: "question",
  problem: "problem",
  solution: "solution",
  hint: "hint",
  answer: "answer",
  exercise: "exercise",
  aside: "aside",
  activity: "activity",
  project: "project",
  investigation: "investigation",
  exploration: "exploration",
  figure: "figure",
  table: "table",
  enumerate: "ol",
  itemize: "ul",
};
