// Purpose: Contains constants used throughout the project.

export const BLOCKS: { [key: string]: string } = {
  axiom: "axiom",
  principle: "principle",
  conjecture: "conjecture",
  heuristic: "heuristic",
  hypothesis: "hypothesis",
  assumption: "assumption",
  theorem: "theorem",
  thm: "theorem",
  lemma: "lemma",
  lem: "lemma",
  corollary: "corollary",
  cor: "corollary",
  claim: "claim",
  proposition: "proposition",
  prop: "proposition",
  algorithm: "algorithm",
  fact: "fact",
  identity: "identity",
  proof: "proof",
  definition: "definition",
  def: "definition",
  defn: "definition",
  remark: "remark",
  note: "note",
  warning: "warning",
  convention: "convention",
  observation: "observation",
  insight: "insight",
  example: "example",
  question: "question",
  problem: "problem",
  solution: "solution",
  hint: "hint",
  answer: "answer",
  exercise: "exercise",
  aside: "aside",
  activity: "activity",
  project: "project",
  investigation: "investigation",
  exploration: "exploration",
  figure: "figure",
  table: "table",
  enumerate: "ol",
  itemize: "ul",
};
